### ISSUE TITLE
Select game language

### ISSUE THREAD

**Issue by ceesvanegmond** [coc4tm/OurLoader#6]
OurLoader works perfectly, I can finally play my JP games on my EU WiiU! There's one issue, for example, when playing Zelda Twilight Princess JP import, the text in the game is still in English. Any idea on how to fix this? Same goes for Hyrule Warriors JP import. Any idea?

**Comment by coc4tm** [comment]
I have really no idea ...
Game is loaded with console language . And i think you can't select japenaese language on EU console .

**Comment by coc4tm** [comment]
It's time to close this .
I think there is no way to select game language aside change console language.
